---
title: "BenchMark_Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE}
plot(pressure)

library(ggplot2)
```

```{r evaluate the correlation between the size metrics of and project effort}
#Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

#ucp_data <- UCP_Dataset
#ucp_data <- UCP_Dataset_OnlineV1.1

ucp_data <- read.csv("UCP_Dataset_OnlineV1.1.csv")

uc_num <- ucp_data[,"Simple_UC"] + ucp_data[,"Average_UC"]+ucp_data[,"Complex_UC"]
cor(uc_num, ucp_data$Real_Effort_Person_Hours)
ucp_data$uc_num <- uc_num
print(cor(ucp_data$uc_num, ucp_data$Real_Effort_Person_Hours))
print(cor.test(ucp_data$uc_num,ucp_data$Real_Effort_Person_Hours))
lm(Real_Effort_Person_Hours~uc_num, data=ucp_data)

ucp <- (ucp_data[,"UAW"] + ucp_data[,"UUCW"])*ucp_data[,"EF"]*ucp_data[,"TCF"]
ucp_data$UCP <- ucp
print(cor(ucp_data$UCP, ucp_data$Real_Effort_Person_Hours))

ggplot(ucp_data, aes(x = UCP, y = Real_P20)) +
  geom_point(shape = 1) + stat_smooth(method = "lm",  se = FALSE, fullrange = TRUE)

fp_data <- read.csv("china.csv")
fp_num <- fp_data[,"Input"]+fp_data[,"Output"]+fp_data[,"Enquiry"];
fp_data$fp_num <- fp_num
cor(fp_data$fp_num, fp_data$Effort)

print(cor.test(fp_data$fp_num,fp_data$Effort))
  
```

```{r evaluate the correlation matrix from the benchmark dataset}
transaction_data <- read.csv('correlation-benchmark-11-11.csv')
rownames(transaction_data) <- transaction_data$Project
transaction_data$Project <- NULL
tran_cor <- cor(transaction_data)
tran_cor['KSLOC', 'Effort'] = 0.647
tran_cor['Effort', 'KSLOC'] = 0.647
tran_cor['Component', 'Effort'] = 0.626
tran_cor['Effort', 'Component'] = 0.626
print(tran_cor)

library(corrplot)
corrplot(tran_cor, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```

```{r evaluate the correlation between size metrics and project effort}
shilhavy <- read.csv("UCP_Dataset_OnlineV1.1.csv")
cor(shilhavy$Real_Effort_Person_Hours, shilhavy$Simple_UC+shilhavy$Average_UC+shilhavy$Complex_UC)
cor.test(shilhavy$Real_Effort_Person_Hours, shilhavy$Simple_UC+shilhavy$Average_UC+shilhavy$Complex_UC)

albrecht <- read.csv("albrecht.csv")
cor(albrecht$Effort, albrecht$Input+albrecht$Output+albrecht$Inquiry)
cor.test(albrecht$Effort, albrecht$Input+albrecht$Output+albrecht$Inquiry)

china <- read.csv("china.csv")
cor(china$Effort, china$Input+china$Output+china$Enquiry)
cor.test(china$Effort, china$Input+china$Output+china$Enquiry)

kemerer <- read.csv("kemerer.csv")
cor(kemerer$EffortMM, kemerer$KSLOC)
cor.test(kemerer$EffortMM, kemerer$KSLOC)

miyazaki94 <- read.csv("miyazaki94.csv")
cor(miyazaki94$KLOC, miyazaki94$MM)
cor.test(miyazaki94$KLOC, miyazaki94$MM)
```

```{r evaluate the contribution of software function size}
influential_ratio_1 = mean(1-abs(shilhavy$UUCP-shilhavy$ucp)/shilhavy$UCP)

influential_ratio_2 = mean(1-abs(albrecht$FPAdj-1))


```

