---
title: "Report"
author: "Zichong, kqi"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r}

my_data1 <- read.csv('./cocomonasa_2.csv',stringsAsFactors= T)
my_data3 <- read.csv('./UMLx_d1_577.csv',stringsAsFactors= T)
my_data2 <- read.csv('./china.csv',stringsAsFactors= T)
my_data4 <- read.csv('./Silhavy.csv',stringsAsFactors= T)
#summary(data)

```

```{r}

#turn the effort data of csv_result-cocomonasa_2 file and modelEvaluations-9-29 file into data frame
effort <- data.frame(my_data1$act_effort)
colnames(effort) <-c('val')
Effort <- data.frame(my_data3$Effort)
colnames(Effort)<-c('val')
library(ggplot2)
#mark the data using column values
effort$short <- 'effort1'
Effort$short <- 'Effort3'
#combine the data into one
comparison2 <- rbind(effort,Effort)

#draw the plot with histgram and density curve combined
ggplot(comparison2, aes(val, fill = short)) + geom_density(alpha = 0.2) + geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')

```

```{r}
#turn the effort data of csv_result-cocomonasa_2 file and china file into data frame
effort2 <- data.frame(my_data2$Effort)
colnames(effort2) <-c('val')
Effort <- data.frame(my_data3$Effort)
colnames(Effort)<-c('val')
#mark the data using column values
effort2$short <- 'effort2'
Effort$short <- 'Effort3'
#combine the data into one
comparison3 <- rbind(effort2,Effort)

#draw the plot with histgram and density curve combined
ggplot(comparison3, aes(val, fill = short)) + geom_density(alpha = 0.2) + geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')

#turn the  equivphyskloc data of csv_result-cocomonasa_2 file and KSLOC data of modelEvaluations-9-29 file into data frame
equiv <- data.frame(my_data1$equivphyskloc)
colnames(equiv) <-c('val')
ksloc <- data.frame(my_data3$KSLOC * 1000)
colnames(ksloc)<-c('val')
#mark the data using column values
equiv$short <- 'equiv'
ksloc$short <- 'ksloc'
#combine the data into one
comparison1 <- rbind(equiv,ksloc)

#draw the plot with histgram and density curve combined
ggplot(comparison1, aes(val, fill = short)) + geom_density(alpha = 0.2)  + geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')

#turn the combined data of effort data and KSLOC data of modelEvaluations-9-29 file into data frame
combined3 <- data.frame(my_data3$KSLOC*1000,my_data3$Effort)
#turn the combined data of effort data and equiv data of csv_result-cocomonasa_2 file into data frame
combined1 <- data.frame(my_data1$equivphyskloc,my_data1$act_effort)

colnames(combined1) <- c('val','effort')
colnames(combined3) <- c('val','effort')
#mark the data using column values
combined1$id <- 1
combined3$id <- 3
#combine the data into one
comparison6 <- rbind(combined1,combined3)

#draw the scatter plot with data points
ggplot(comparison6, aes(x = val, y = effort, color = id)) + geom_point()

```

```{r}
#turn the  sun of num of input, output and enquiry of china file and transaction number data of modelEvaluations-9-29 file into data frame
num2 <- data.frame(my_data2$Input+my_data2$Output+my_data2$Enquiry)
colnames(num2) <-c('val')
num3 <- data.frame(my_data3$Tran_Num)
colnames(num3)<-c('val')
#mark the data using column values
num2$short <- 'Tran_num2'
num3$short <- 'Tran_num3'
#combine the data into one
comparison4 <- rbind(num2,num3)
#draw the plot with histgram and density curve combined
ggplot(comparison4, aes(val, fill = short)) + geom_density(alpha = 0.2)  + geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')

#turn the num of usecase data of modelEvaluations-9-29 and UCP_Dataset_OnlineV1.0 file into data file
Usecase_num3 <- data.frame(my_data3$UseCase_Num)
colnames(Usecase_num3) <- c('val')
Usecase_num4 <- data.frame(my_data4$Use_Case_Num)
colnames(Usecase_num4) <- c('val')
#mark the data using column values
Usecase_num3$short <- 'U3'
Usecase_num4$short <- 'U4'
#combine the data into one
comparison5 <- rbind(Usecase_num3,Usecase_num4)
#draw the plot with histgram and density curve combined
ggplot(comparison5, aes(val, fill = short)) + geom_density(alpha = 0.2) + geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')
```