---
title: "Transaction Weight Calibration Visualized"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("utils/feature_selection.R")
source("utils/data_selection.R")
source("utils/model_funcs.R")
source("accuracy_confidence_evaluation.R")
source("transaction_based_model.R")
source("size_metric_based_models.R")
library(jsonlite)
library(reshape)
library(tidyverse)
library(fitdistrplus)
library(egg)
library(gridExtra)
library(plyr)
require(MASS)

```
Combined Data Effort Values
```{r descriptive statistics, fig.width=5,fig.height=2.5}
modelData <- selectData("dsets/modelEvaluations-1-3.csv")
rownames(modelData) <- modelData$Project
modelData$Project <- NULL
```

#load the comparative models. Each model for comparison should include two functions for evaluateion:
#1. model_train(dataset)
#2. model_predict(dataset)

```{r swtiii, warning = FALSE}

#initialize models for training, testing, and evaluation. The models are put into a list with model names referencing a list of hyper-parameters, which will be passed to the model training function.

models = list()

#first perform model search for the swtiii parameters
SWTIIIresults <- performSearch(1, modelData, c("TL", "TD", "DETs"))
#intialize the model with hyper parameters (cutpoints) decided by cross validatoin results for different ways of binning
SWTIIIModelSelector <- 1
models$tm1 = trainsaction_based_model(SWTIIIresults, SWTIIIModelSelector)

#initialize the size metric based models
size_models <- size_metric_models()
models = append(models, size_models)

#load the machine learning based models
#to create a model, following 3 steps:
# 1.create the model training function by rewriting this following template function
#  m_fit.MODEL_NAME <- function(MODEL_NAME,dataset){}
# 2.create the prediction function by rewriting this following template function
#  m_predict.MODEL_NAME <- function(MODEL_NAME, testData){}
# 3.add your model name into the "models"(above) variable for referencing
#  models.MODEL_NAME <- list(params...)
# examples can be found in the size_metric_based_models.R or transaction_based_model.R
  
```
comparison between the candidate models SWTIII, UCP, COCOMO, a-priori COCOMO using cross-validation
```{r modelPlot, warning = FALSE, fig.width=5,fig.height=4}

benchmarkResults <- modelBenchmark(models, modelData)

avgPreds <- benchmarkResults[["avgPreds"]]
avgPreds <- data.frame(avgPreds)
meltAvgPreds = melt(avgPreds, id.vars="Pred")
colnames(meltAvgPreds) <- c("Pred", "Method", "Value")

print("melt avg preds info")
ggplot(meltAvgPreds) + theme_bw() + geom_point(aes(x=Pred, y=Value, group=Method,color=Method),size=3)+ xlab("Relative Deviation (%)") +
				ylab("Percentage of Estimates <= x%")+ theme(legend.position="bottom")

print("melt avg preds info as lines and smooth function")
ggplot(meltAvgPreds) + theme_bw() + 
		geom_line(aes(y=Value, x=Pred, group=Method,color=Method)) +
		stat_smooth(aes(y=Value, x=Pred, group=Method,color=Method), method = lm, formula = y ~ poly(x, 10), se = FALSE)+ xlab("Relative Deviation (%)") +
		ylab("Percentage of Estimates <= x%")+ theme(legend.position="bottom")


print("melt avg preds info as dots and smooth function")
ggplot(meltAvgPreds) + theme_bw() + 
		geom_point(aes(x=Pred, y=Value, group=Method,color=Method,shape=Method),size=1.5) +
		scale_shape_manual(values=c(0,1,2,3,4,5,6,7,8,9,10))+
		stat_smooth(aes(x=Pred, y=Value, group=Method,color=Method), method = lm, formula = y ~ poly(x, 10), se = FALSE)+ xlab("Relative Deviation (%)") +
		ylab("Percentage of Estimates <= x%")+ theme(legend.position="bottom")
```
