## Functions
```{r}
library(mvtnorm)
calculateSWTI <- function(x, weights) {
  # Calculates SWTI.
  #
  # Args:
  #   x: vector containing transaction length data.
  #   weights: Vector of weight to apply to each transaction after 
  #     discretization and classification. Weights must be sorted from least 
  #     complex to most complex.
  #
  # Returns: 
  #   SWTI
  quantiles <- seq(1/length(weights),1 - (1/length(weights)), 1/length(weights))
  print("quntiles")
  print(quantiles)
  cutPoints <- qnorm(quantiles, mean = mean(x), sd = sd(x))
  #print("cutPoints")
  #print(cutPoints)
  category <- cut(x, c(-Inf, cutPoints, Inf), labels = FALSE)
  print("category")
  print(category)
  SWTI <- 0
  for (num in category) {
    SWTI <- SWTI + weights[num]
  }
  SWTI
}

calculateSWTII <- function(x, weights) {
  # Calculates SWTII.
  #
  # Args:
  #   x: Dataframe containing transaction length and transaction degree data.
  #   weights: Vector of weight to apply to each transaction after 
  #     discretization and classification. Weights must be sorted from least 
  #     complex to most complex.
  #
  # Returns: 
  #   SWTII
  quantiles <- seq(1/length(weights),1 - (1/length(weights)), 1/length(weights))
  cutPoints <- c(-Inf, quantiles, Inf)
  dataMeans <- c(mean(x$TL), mean(x$TD))
  dataCovariance <- cov(as.matrix(subset(x, select = c("TL", "TD"))))
  percentiles <- vector(length = nrow(x))
  for (i in seq(1, nrow(x))) {
    TL <- x[i, "TL"]
    TD <- x[i, "TD"]
    percentiles[i] <- 
      pmvnorm(lower = -Inf, upper = c(TL, TD), mean = dataMeans, sigma = dataCovariance)
    #print("swt II parameters")
    #print(percentiles[i])
  }
  category <- cut(percentiles, cutPoints, labels = FALSE)
  print(category)
  SWTII <- 0
  for (num in category) {
    SWTII <- SWTII + weights[num]
  }
  SWTII
}

calculateSWTIII <- function(x, weights) {
  # Calculates SWTIII.
  #
  # Args:
  #   x: Dataframe containing transaction length, transaction degree, and DET 
  #      data.
  #   weights: Vector of weight to apply to each transaction after 
  #     discretization. Weights must be sorted from least complex to most complex.
  #
  # Returns: 
  #   SWTIII
  quantiles <- seq(1/length(weights),1 - (1/length(weights)), 1/length(weights))
  cutPoints <- c(-Inf, quantiles, Inf)
  dataMeans <- c(mean(x$TL), mean(x$TD), mean(x$DETs))
  dataCovariance <- cov(as.matrix(subset(x, select = c("TL", "TD", "DETs"))))
  percentiles <- vector(length = nrow(x))
  for (i in seq(1, nrow(x))) {
    TL <- x[i, "TL"]
    TD <- x[i, "TD"]
    DETs <- x[i, "DETs"]
    percentiles[i] <- 
      pmvnorm(lower = -Inf, upper = c(TL, TD, DETs), mean = dataMeans, sigma = dataCovariance)
  }
  category <- cut(percentiles, cutPoints, labels = FALSE)
  SWTIII <- 0
  for (num in category) {
    SWTIII <- SWTIII + weights[num]
  }
  SWTIII
}

calcMMRE <- function(testData, pred) {
  # Calculates mean magnitude relative error (MMRE).
  #
  # Args:
  #   testData: known results to validate against
  #   pred: predicted results from the model
  #
  # Returns:
  #   MMRE
  mmre <- abs(testData - pred)/testData
  mean_value <- mean(mmre)
  mean_value
}

calcPRED <- function(testData, pred, percent) {
  # Calculates percentage relative error deviation (PRED).
  #
  # Args:
  #   testData: known results to validate against
  #   pred: predicted results from the model
  #   percent: percent error threshold to accept predicted value
  #
  # Returns:
  #   PRED
  value <- abs(testData - pred)/testData
  percent_value <- percent/100
  pred_value <- value <= percent_value
  mean(pred_value)
}
```
## Cross validation
Get the data
```{r}
transactionAnalyticsFolder <- "C:/Users/flyqk/Documents/Google Drive/ResearchSpace/Research Projects/UMLx/data/FeatureSelection/Transaction Data"
data <- matrix(nrow = length(dir(transactionAnalyticsFolder)), ncol = 4)
colnames(data) <- c("SWTI", "SWTII", "SWTIII", "Effort")
rownames(data) <- dir(transactionAnalyticsFolder)
weights <- c(3,5,10)
for (file in dir(transactionAnalyticsFolder)) {
  transactionAnalytics <- read.csv(paste(transactionAnalyticsFolder, file, sep="/"))
  transactionAnalytics <- subset(transactionAnalytics, select = c("TL", "TD", "DETs"))
  data[file, "SWTI"] <- calculateSWTI(transactionAnalytics$TL, weights)
  data[file, "SWTII"] <- calculateSWTII(transactionAnalytics, weights)
  data[file, "SWTIII"] <- calculateSWTIII(transactionAnalytics, weights)
}
data[, "Effort"] <- c(263, 268.5, 1482.5, 1392, 804.5, 3113, 1592)
data <- as.data.frame(data)
```
SWTI
```{r}
k <- 5
folds <- cut(seq(1, nrow(data)), breaks = k, labels = FALSE)
foldMMREResults <- vector(length = k)
foldPREDResults <- vector(length = k)
for (i in 1:k) {
  testIndexes <- which(folds == i, arr.ind = TRUE)
  testData <- data[testIndexes, ]
  trainData <- data[-testIndexes, ]
  model <- lm(Effort ~ SWTI, data = trainData)
  predicted <- predict.lm(model, newdata = testData)
  foldMMREResults[i] <- calcMMRE(testData$Effort, predicted)
  foldPREDResults[i] <- calcPRED(testData$Effort, predicted, 25)
}
meanMMRE <- mean(foldMMREResults)
meanPRED <- mean(foldPREDResults)
meanMMRE
meanPRED
```
SWTII
```{r}
k <- 5
folds <- cut(seq(1, nrow(data)), breaks = k, labels = FALSE)
foldMMREResults <- vector(length = k)
foldPREDResults <- vector(length = k)
for (i in 1:k) {
  testIndexes <- which(folds == i, arr.ind = TRUE)
  testData <- data[testIndexes, ]
  trainData <- data[-testIndexes, ]
  model <- lm(Effort ~ SWTII, data = trainData)
  predicted <- predict.lm(model, newdata = testData)
  foldMMREResults[i] <- calcMMRE(testData$Effort, predicted)
  foldPREDResults[i] <- calcPRED(testData$Effort, predicted, 25)
}
meanMMRE <- mean(foldMMREResults)
meanPRED <- mean(foldPREDResults)
meanMMRE
meanPRED
```
SWTIII
```{r}
k <- 5
folds <- cut(seq(1, nrow(data)), breaks = k, labels = FALSE)
foldMMREResults <- vector(length = k)
foldPREDResults <- vector(length = k)
for (i in 1:k) {
  testIndexes <- which(folds == i, arr.ind = TRUE)
  testData <- data[testIndexes, ]
  trainData <- data[-testIndexes, ]
  model <- lm(Effort ~ SWTIII, data = trainData)
  predicted <- predict.lm(model, newdata = testData)
  foldMMREResults[i] <- calcMMRE(testData$Effort, predicted)
  foldPREDResults[i] <- calcPRED(testData$Effort, predicted, 25)
}
meanMMRE <- mean(foldMMREResults)
meanPRED <- mean(foldPREDResults)
meanMMRE
meanPRED
```