---
title: "Transaction Weight Calibration Visualized"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("transaction_weights_calibration4.R")
source("comparison_between_size_metrics.R")
library(jsonlite)
library(reshape)
library(tidyverse)
library(fitdistrplus)
library(egg)
library(gridExtra)
library(plyr)

cutsAsVec <- function(x) {
  ret <- c("Cut Points:")
  for (row in rownames(x)) {
    cutPoints <- round(x[row, ], digits = 1)
    ret <- c(ret, paste(row,":", paste(cutPoints, collapse = ", ")))
  }
  ret
}
```
Combined Data Effort Values
```{r combined}
modelData <- read.csv("modelEvaluations-8-30-2.csv")
modelData$Project <- as.character(modelData$Project)
modelData$transaction_file <- as.character(modelData$transaction_file)
effort <- subset(modelData, select=c("Effort"))
transactionFiles <- subset(modelData, select=c("transaction_file"))
rownames(effort) <- modelData$Project
rownames(transactionFiles) <- modelData$Project
combined <- combineData(transactionFiles)

ggplot(modelData, aes(x=UseCase_Num)) + 
  geom_histogram(binwidth=5, colour="black", fill="gray") + 
  xlab("Number of Use Case") + ylab("Number of Projects") + ggtitle("Project Distribution - Use Case")+
  theme_bw(base_size=20)

ggplot(modelData, aes(x=KSLOC)) + 
  geom_histogram(binwidth=0.5, colour="black", fill="gray") + 
  xlab("KSLOC") + ylab("Number of Projects") + ggtitle("Project Distribution - SLOC") + 
   theme_bw(base_size=20)

ggplot(modelData, aes(x=Personnel)) + 
  geom_histogram(binwidth=1, colour="black", fill="gray") + 
  xlab("Personnel") + ylab("Number of Projects") + ggtitle("Project Distribution - Personnel") + 
   theme_bw(base_size=20)

ggplot(modelData, aes(x=Effort)) + 
  geom_histogram(binwidth=300, colour="black", fill="gray") + 
  xlab("Effort") + ylab("Number of Projects") + ggtitle("Project Distribution - Effort") + 
   theme_bw(base_size=20)

unique.levels <- sort(unique(modelData$Type))
count <- table(modelData$Type)
count.modelData <- data.frame(unique.levels, count)

ggplot(count.modelData, aes(unique.levels, count)) + 
  geom_bar(stat="identity", colour="black", fill="gray") + 
  xlab("Project Type") + ylab("Number of Projects") + ggtitle("Project Distribution - Type") + 
   theme_bw(base_size=20)


#effort$Project <- NULL
ggplot(combined, aes(x=TL)) + 
  geom_histogram(aes(y = ..density..), binwidth=1, colour="black", fill="white") + 
  #stat_function(fun = dnorm, args = list(mean = mean(combined$TL), sd(combined$TL))) + 
  stat_function(fun = dgamma, args = list(shape=6.543586, rate=1.160249)) + 
  xlab("TL") + ggtitle("Combined TL Data Summary") + 
  annotate("text", x=14, y=0.25, label= "Gamma: shape=6.54, rate=1.16; KS: p-value < 0.01")+
  theme_bw()

ggplot(combined, aes(x=TD)) + 
  geom_histogram(aes(y = ..density..), binwidth=0.5, colour="black", fill="white") + 
  #stat_function(fun = dnorm, args = list(mean = mean(combined$TD), sd(combined$TD))) +
  stat_function(fun = dgamma, args = list(shape=3.6492150, rate=0.6985361 )) +
  annotate("text", x=16, y=0.18, label= "Gamma: shape=3.65, rate=0.70; KS: p-value < 0.01")+
  xlab("TD") + ggtitle("Combined TD Data Summary") + 
  theme_bw()

ggplot(combined, aes(x=DETs)) + 
  geom_histogram(aes(y = ..density..), binwidth=1, colour="black", fill="white") + 
  #stat_function(fun = dnorm, args = list(mean = mean(combined$DETs), sd(combined$DETs))) + 
  stat_function(fun = dgamma, args = list(shape=1.6647412, rate=0.1691911)) + 
  annotate("text", x=57, y=0.15, label= "Gamma: shape=1.66, rate=0.17; KS: p-value < 0.01")+
  xlab("DETs") + ggtitle("Combined DETs Data Summary") + 
  theme_bw()

selectedModels = list()
```
TN Search Results
```{r swti part I} 
TNresults <- performSearch(6, effort, transactionFiles, c())
# Plot classification results
for (i in 1:length(TNresults)) {
  result <- TNresults[[i]]
  df <- as.data.frame(t(subset(result$data, select = -c(Effort))))
  g <- ggplot(data = df, aes(x = rownames(df), y = Aggregate)) + 
    geom_bar(stat = "identity") +
     xlab("Levels") +
    ylab("Counts") +
    ggtitle(paste("Classification Results:", i, "levels"))
  cutsVec <- cutsAsVec(result$cuts)
  g <- g + geom_text(data = data.frame(cutsVec), aes(label=cutsVec, col=cutsVec), alpha=0, x=1, y=1) +
  theme(legend.key=element_blank(), legend.title = element_blank()) +
  guides(colour=guide_legend(override.aes=list(size=0)), reverse = TRUE) + 
  theme_bw()
  print(g)
}

# Plot predicted vs. actual effort values
predictedValuesTN <- sapply(1:length(TNresults), function(i) {
  predicted <- apply(TNresults[[i]]$data, 1, function(x) {
    blmpredicted <- predict.blm(TNresults[[i]]$model, newdata = as.data.frame(t(x)))
    #blmpredicted*TNresults[[i]]$normFactor
  })
})

colnames(predictedValuesTN) <- paste(1:length(TNresults), "Bins")
predictedValuesTN <- subset(predictedValuesTN, rownames(predictedValuesTN) != "Aggregate")
#print(predictedValuesTN)
predictedValuesTN <- merge(as.data.frame(predictedValuesTN), effort, by='row.names', all=TRUE)
rownames(predictedValuesTN) <- predictedValuesTN$Row.names
predictedValuesTN$Row.names <- NULL

r2Vals <- apply(subset(predictedValuesTN, select = -Effort), 2, function (x) {
  dat <- data.frame(Predicted = x, Effort = predictedValuesTN$Effort)
  model <- lm(Effort ~ ., data = dat)
  summary(model)$r.squared
})
r2Vals <- round(r2Vals, digits = 5)
r2Vals <- paste("r2:", r2Vals, sep = "")
predictedValues <- gather(predictedValuesTN, numBins, Predicted, -Effort)
r2data_txt <- data.frame(label = as.character(r2Vals), numBins = paste(1:length(TNresults), "Bins"))
ggplot(predictedValues, aes(x = Predicted, y = Effort)) +
  geom_point(shape = 1) + stat_smooth(method = "lm",  se = FALSE, fullrange = TRUE) +
  facet_grid(. ~ numBins, scales = "free") + xlab("Predicted Effort") +
  ylab("Actual Effort") + ggtitle("Goodness of Fit") +
  theme(panel.spacing = unit(1, "lines")) +
  geom_text(data = r2data_txt, size = 3, mapping = aes(x = -Inf, y = -Inf, label = label),
            hjust = -0.1, vjust = -1) + 
  theme_bw()

# Plot cross validation results
MSEdata <- data.frame(NumBins = 1:length(TNresults), MSE = sapply(TNresults, function(x) { x$MSE }))
MMREdata <- data.frame(NumBins = 1:length(TNresults), MMRE = sapply(TNresults, function(x) { x$MMRE }))
PREDdata <- data.frame(NumBins = 1:length(TNresults), PRED = sapply(TNresults, function(x) { x$PRED }))
ggplot(data = MSEdata, aes(x = NumBins, y = log(MSE))) + geom_point(shape = 1) + geom_line() + ggtitle("MSE vs Number of Bins") +  theme_bw()
ggplot(data = MMREdata, aes(x = NumBins, y = MMRE)) + geom_point(shape = 1) + geom_line() + ggtitle("MMRE vs Number of Bins") +  theme_bw()
ggplot(data = PREDdata, aes(x = NumBins, y = PRED)) + geom_point(shape = 1) + geom_line() + ylab("PRED(0.25)") + ggtitle("PRED(0.25) Results") +  theme_bw()

# Plot marginal posteriors for each parameter
for (i in 1:length(TNresults)) {
  marginalData <- TNresults[[i]]$model[, !names(TNresults[[i]]$model) %in% c("(Intercept)", "sigma")]
  if (is.vector(marginalData)) {
    marginalData <- data.frame(l1 = marginalData)
  }
  for (col in names(marginalData)) {
    mean <- mean(marginalData[, col])
    sd <- sd(marginalData[, col])
    peakDensity <- dnorm(mean, mean, sd)
    g <- ggplot(marginalData, aes(x=marginalData[, col])) + 
    geom_histogram(aes(y = ..density..), binwidth = 1, colour="black", fill="white") + 
    stat_function(fun = dnorm, args = list(mean = mean(mean), sd = sd)) + 
    xlab(col) + ggtitle("Posterior Weight", paste(col, i, "bins")) +
    annotate("text", x = mean, y = peakDensity * ((sd/3 *.1) + 1), label = paste("mean:", round(mean,2),",", "sd:", round(sd,2))) + 
    theme_bw()
    print(g)
  }
}
```

SWTI Search Results I
```{r swti part I} 
SWTIresults <- performSearch(6, effort, transactionFiles, c("TL"))
# Plot classification results
for (i in 1:length(SWTIresults)) {
  result <- SWTIresults[[i]]
  df <- as.data.frame(t(subset(result$data, select = -c(Effort))))
  g <- ggplot(data = df, aes(x = rownames(df), y = Aggregate)) + 
    geom_bar(stat = "identity") +
    xlab("Levels") +
    ylab("Counts") +
    ggtitle(paste("Classification Results:", i, "levels"))+
    theme_bw()
  cutsVec <- cutsAsVec(result$cuts)
  g <- g + geom_text(data = data.frame(cutsVec), aes(label=cutsVec, col=cutsVec), alpha=0, x=1, y=1) +
  theme(legend.key=element_blank(), legend.title = element_blank())
  guides(colour=guide_legend(override.aes=list(size=0)), reverse = TRUE) + 
  print(g)
}

categorizedTransactions = matrix(nrow=0, ncol=3)
colnames(categorizedTransactions) <- c("Counts", "Bins", "Classification")

for (i in 1:length(SWTIresults)) {
  result <- SWTIresults[[i]]
  df <- as.data.frame(t(subset(result$data, select = -c(Effort))))
  rownames(df) <- c(paste("b", seq(1, nrow(df)), sep=""))
  #print(rep(paste(i, "Bins", sep=" "), nrow(df)))
  mergedTransactionCounts = cbind(as.matrix(rowSums(df)), rownames(df), rep(paste(i, "Bins", sep=" "), nrow(df)))
  rownames(mergedTransactionCounts) <- NULL
  categorizedTransactions <- rbind(categorizedTransactions, mergedTransactionCounts)
}
  #print(categorizedTransactions)

categorizedTransactions = as.data.frame(categorizedTransactions)
categorizedTransactions$Counts <- as.numeric(as.character(categorizedTransactions$Counts))
  
   g <- ggplot(data = categorizedTransactions, aes(x = Bins, y = Counts)) + 
    geom_bar(stat = "identity") +
      facet_wrap(. ~ Classification, scales = "free", nrow=2)+
    xlab("Bins") +
    ylab("Counts") +
    ggtitle(paste("Discretization Results:", i, "bins"))+
    theme_bw(base_size=12)
  print(g)
  
# Plot predicted vs. actual effort values
predictedValuesSWTI_I <- sapply(1:length(SWTIresults), function(i) {
  predicted <- apply(SWTIresults[[i]]$data, 1, function(x) {
    blmpredicted <- predict.blm(SWTIresults[[i]]$model, newdata = as.data.frame(t(x)))
    #blmpredicted*SWTIresults[[i]]$normFactor
  })
})
colnames(predictedValuesSWTI_I) <- paste(1:length(SWTIresults), "Bins")
predictedValuesSWTI_I <- subset(predictedValuesSWTI_I, rownames(predictedValuesSWTI_I) != "Aggregate")
#print(predictedValuesSWTI_I)
predictedValuesSWTI_I <- merge(as.data.frame(predictedValuesSWTI_I), effort, by='row.names', all=TRUE)
rownames(predictedValuesSWTI_I) <- predictedValuesSWTI_I$Row.names
predictedValuesSWTI_I$Row.names <- NULL
r2Vals <- apply(subset(predictedValuesSWTI_I, select = -Effort), 2, function (x) {
  dat <- data.frame(Predicted = x, Effort = predictedValuesSWTI_I$Effort)
  model <- lm(Effort ~ ., data = dat)
  summary(model)$r.squared
})
r2Vals <- round(r2Vals, digits = 5)
r2Vals <- paste("r2:", r2Vals, sep = "")
predictedValues <- gather(predictedValuesSWTI_I, numBins, Predicted, -Effort)
r2data_txt <- data.frame(label = as.character(r2Vals), numBins = paste(1:length(SWTIresults), "Bins"))
ggplot(predictedValues, aes(x = Predicted, y = Effort)) +
  geom_point(shape = 1) + stat_smooth(method = "lm",  se = FALSE, fullrange = TRUE) +
  facet_grid(. ~ numBins, scales = "free") + xlab("Predicted Effort") +
  ylab("Actual Effort") + ggtitle("Goodness of Fit") +
  theme(panel.spacing = unit(1, "lines")) +
  geom_text(data = r2data_txt, size = 3, mapping = aes(x = -Inf, y = -Inf, label = label),
            hjust = -0.1, vjust = -1) + 
  theme_bw()

# Plot cross validation results
MSEdata <- data.frame(NumBins = 1:length(SWTIresults), MSE = sapply(SWTIresults, function(x) { x$MSE }))
MMREdata <- data.frame(NumBins = 1:length(SWTIresults), MMRE = sapply(SWTIresults, function(x) { x$MMRE }))
PREDdata <- data.frame(NumBins = 1:length(SWTIresults), PRED = sapply(SWTIresults, function(x) { x$PRED }))
ggplot(data = MSEdata, aes(x = NumBins, y = log(MSE))) + geom_point(shape = 1) + geom_line() + ggtitle("MSE vs Number of Bins") + 
  theme_bw()
ggplot(data = MMREdata, aes(x = NumBins, y = MMRE)) + geom_point(shape = 1) + geom_line() + ggtitle("MMRE vs Number of Bins") + 
  theme_bw()
ggplot(data = PREDdata, aes(x = NumBins, y = PRED)) + geom_point(shape = 1) + geom_line() + ylab("PRED(0.25)") + ggtitle("PRED(0.25) Results") + 
  theme_bw()

# Plot marginal posteriors for each parameter
for (i in 1:length(SWTIresults)) {
  marginalData <- SWTIresults[[i]]$model[, !names(SWTIresults[[i]]$model) %in% c("(Intercept)", "sigma")]
  if (is.vector(marginalData)) {
    marginalData <- data.frame(l1 = marginalData)
  }
  for (col in names(marginalData)) {
    mean <- mean(marginalData[, col])
    sd <- sd(marginalData[, col])
    peakDensity <- dnorm(mean, mean, sd)
    g <- ggplot(marginalData, aes(x=marginalData[, col])) + 
    geom_histogram(aes(y = ..density..), binwidth = 1, colour="black", fill="white") + 
    stat_function(fun = dnorm, args = list(mean = mean(mean), sd = sd)) + 
    xlab(col) + ggtitle("Posterior Weight", paste(col, i, "bins")) +
    annotate("text", x = mean, y = peakDensity * ((sd/3 *.1) + 1), label = paste("mean:", round(mean,2),",", "sd:", round(sd,2))) + 
    theme_bw()
    print(g)
  }
}
```

SWTI Search Results II
```{r swti part II}
SWTIresults_II <- performSearch(6, effort, transactionFiles, c("TD"))
# Plot classification results
for (i in 1:length(SWTIresults_II)) {
  result <- SWTIresults_II[[i]]
  df <- as.data.frame(t(subset(result$data, select = -c(Effort))))
  g <- ggplot(data = df, aes(x = rownames(df), y = Aggregate)) + 
    geom_bar(stat = "identity") +
     xlab("Levels") +
    ylab("Counts") +
    ggtitle(paste("Classification Results:", i, "levels"))
  cutsVec <- cutsAsVec(result$cuts)
  g <- g + geom_text(data = data.frame(cutsVec), aes(label=cutsVec, col=cutsVec), alpha=0, x=1, y=1) +
  theme(legend.key=element_blank(), legend.title = element_blank()) +
  guides(colour=guide_legend(override.aes=list(size=0)), reverse = TRUE) + 
  theme_bw()
  print(g)
}

categorizedTransactions = matrix(nrow=0, ncol=3)
colnames(categorizedTransactions) <- c("Counts", "Bins", "Classification")

for (i in 1:length(SWTIresults_II)) {
  result <- SWTIresults_II[[i]]
  df <- as.data.frame(t(subset(result$data, select = -c(Effort))))
  rownames(df) <- c(paste("b", seq(1, nrow(df)), sep=""))
  #print(rep(paste(i, "Bins", sep=" "), nrow(df)))
  mergedTransactionCounts = cbind(as.matrix(rowSums(df)), rownames(df), rep(paste(i, "Bins", sep=" "), nrow(df)))
  rownames(mergedTransactionCounts) <- NULL
  categorizedTransactions <- rbind(categorizedTransactions, mergedTransactionCounts)

}

categorizedTransactions = as.data.frame(categorizedTransactions)
categorizedTransactions$Counts <- as.numeric(as.character(categorizedTransactions$Counts))
  #print(categorizedTransactions)
  
   g <- ggplot(data = categorizedTransactions, aes(x = Bins, y = Counts)) + 
    geom_bar(stat = "identity") +
      facet_wrap(. ~ Classification, scales = "free", nrow=2)+
    xlab("Bins") +
    ylab("Counts") +
    ggtitle(paste("Discretization Results:", i, "bins"))+
    theme_bw(base_size=12)
  print(g)

# Plot predicted vs. actual effort values
predictedValuesSWTI_II <- sapply(1:length(SWTIresults_II), function(i) {
  predicted <- apply(SWTIresults_II[[i]]$data, 1, function(x) {
    blmpredicted <- predict.blm(SWTIresults_II[[i]]$model, newdata = as.data.frame(t(x)))
    #blmpredicted*SWTIresults_II[[i]]$normFactor
  })
})

colnames(predictedValuesSWTI_II) <- paste(1:length(SWTIresults_II), "Bins")
predictedValuesSWTI_II <- subset(predictedValuesSWTI_II, rownames(predictedValuesSWTI_II) != "Aggregate")
predictedValuesSWTI_II <- merge(as.data.frame(predictedValuesSWTI_II), effort, by='row.names', all=TRUE)
rownames(predictedValuesSWTI_II) <- predictedValuesSWTI_II$Row.names
predictedValuesSWTI_II$Row.names <- NULL
#print(predictedValuesSWTI_II)
r2Vals <- apply(subset(predictedValuesSWTI_II, select = -Effort), 2, function (x) {
  dat <- data.frame(Predicted = x, Effort = predictedValuesSWTI_II$Effort)
  model <- lm(Effort ~ ., data = dat)
  summary(model)$r.squared
})
r2Vals <- round(r2Vals, digits = 5)
r2Vals <- paste("r2:", r2Vals, sep = "")
predictedValues <- gather(predictedValuesSWTI_II, numBins, Predicted, -Effort)
r2data_txt <- data.frame(label = as.character(r2Vals), numBins = paste(1:length(SWTIresults_II), "Bins"))
ggplot(predictedValues, aes(x = Predicted, y = Effort)) +
  geom_point(shape = 1) + stat_smooth(method = "lm",  se = FALSE, fullrange = TRUE) +
  facet_grid(. ~ numBins, scales = "free") + xlab("Predicted Effort") +
  ylab("Actual Effort") + ggtitle("Goodness of Fit") +
  theme(panel.spacing = unit(1, "lines")) +
  geom_text(data = r2data_txt, size = 3, mapping = aes(x = -Inf, y = -Inf, label = label),
            hjust = -0.1, vjust = -1) + 
  theme_bw()

# Plot cross validation results
MSEdata <- data.frame(NumBins = 1:length(SWTIresults_II), MSE = sapply(SWTIresults_II, function(x) { x$MSE }))
MMREdata <- data.frame(NumBins = 1:length(SWTIresults_II), MMRE = sapply(SWTIresults_II, function(x) { x$MMRE }))
PREDdata <- data.frame(NumBins = 1:length(SWTIresults_II), PRED = sapply(SWTIresults_II, function(x) { x$PRED }))
ggplot(data = MSEdata, aes(x = NumBins, y = log(MSE))) + geom_point(shape = 1) + geom_line() + ggtitle("MSE vs Number of Bins") + 
  theme_bw()
ggplot(data = MMREdata, aes(x = NumBins, y = MMRE)) + geom_point(shape = 1) + geom_line() + ggtitle("MMRE vs Number of Bins") + 
  theme_bw()
ggplot(data = PREDdata, aes(x = NumBins, y = PRED)) + geom_point(shape = 1) + geom_line() + ylab("PRED(0.25)") + ggtitle("PRED(0.25) Results") + 
  theme_bw()

# Plot marginal posteriors for each parameter
for (i in 1:length(SWTIresults_II)) {
  marginalData <- SWTIresults_II[[i]]$model[, !names(SWTIresults_II[[i]]$model) %in% c("(Intercept)", "sigma")]
  if (is.vector(marginalData)) {
    marginalData <- data.frame(l1 = marginalData)
  }
  for (col in names(marginalData)) {
    mean <- mean(marginalData[, col])
    sd <- sd(marginalData[, col])
    peakDensity <- dnorm(mean, mean, sd)
    g <- ggplot(marginalData, aes(x=marginalData[, col])) + 
    geom_histogram(aes(y = ..density..), binwidth = 1, colour="black", fill="white") + 
    stat_function(fun = dnorm, args = list(mean = mean(mean), sd = sd)) + 
    xlab(col) + ggtitle("Posterior Weight", paste(col, i, "bins")) +
    annotate("text", x = mean, y = peakDensity * ((sd/3 *.1) + 1), label = paste("mean:", round(mean,2),",", "sd:", round(sd,2))) + 
    theme_bw()
    print(g)
  }
}
```

SWTI Search Results III
```{r swti part III}
SWTIresults_III <- performSearch(6, effort, transactionFiles, c("DETs"))
  # Plot classification results
for (i in 1:length(SWTIresults_III)) {
  result <- SWTIresults_III[[i]]
  df <- as.data.frame(t(subset(result$data, select = -c(Effort))))
  g <- ggplot(data = df, aes(x = rownames(df), y = Aggregate)) + 
    geom_bar(stat = "identity") +
      xlab("Levels") +
    ylab("Counts") +
    ggtitle(paste("Discretization Results:", i, "levels"))
  cutsVec <- cutsAsVec(result$cuts)
  g <- g + geom_text(data = data.frame(cutsVec), aes(label=cutsVec, col=cutsVec), alpha=0, x=1, y=1) +
  theme(legend.key=element_blank(), legend.title = element_blank()) +
  guides(colour=guide_legend(override.aes=list(size=0)), reverse = TRUE) + 
  theme_bw()
  print(g)
}

categorizedTransactions = matrix(nrow=0, ncol=3)
colnames(categorizedTransactions) <- c("Counts", "Bins", "Classification")
for (i in 1:length(SWTIresults_III)) {
  result <- SWTIresults_III[[i]]
  df <- as.data.frame(t(subset(result$data, select = -c(Effort))))
  rownames(df) <- c(paste("b", seq(1, nrow(df)), sep=""))
  #print(rep(paste(i, "Bins", sep=" "), nrow(df)))
  mergedTransactionCounts = cbind(df$Aggregate, rownames(df), rep(paste(i, "Bins", sep=" "), nrow(df)))
  names(mergedTransactionCounts) <- c("Counts", "Bins", "Classification")
  rownames(mergedTransactionCounts) <- NULL
  categorizedTransactions <- rbind(categorizedTransactions, mergedTransactionCounts)
  
}
categorizedTransactions = as.data.frame(categorizedTransactions)
categorizedTransactions$Counts <- as.numeric(as.character(categorizedTransactions$Counts))
  
   ggplot(data = categorizedTransactions, aes(x = rownames(categorizedTransactions), y = Counts)) + 
    geom_bar(stat = "identity") +
    facet_wrap(. ~ Classification, scales="free", nrow=2)+
    xlab("Bins") +
    ylab("Counts") +
    ggtitle(paste("Discretization Results:", i, "bins"))+
    theme_bw(base_size=12)

# Plot predicted vs. actual effort values
predictedValuesSWTI_III <- sapply(1:length(SWTIresults_III), function(i) {
  predicted <- apply(SWTIresults_III[[i]]$data, 1, function(x) {
    blmpredicted <- predict.blm(SWTIresults_III[[i]]$model, newdata = as.data.frame(t(x)))
    #blmpredicted*SWTIresults_III[[i]]$normFactor
  })
})
colnames(predictedValuesSWTI_III) <- paste(1:length(SWTIresults_III), "Bins")
predictedValuesSWTI_III <- subset(predictedValuesSWTI_III, rownames(predictedValuesSWTI_III) != "Aggregate")
predictedValuesSWTI_III <- merge(as.data.frame(predictedValuesSWTI_III), effort, by='row.names', all=TRUE)
rownames(predictedValuesSWTI_III) <- predictedValuesSWTI_III$Row.names
predictedValuesSWTI_III$Row.names <- NULL
#print(predictedValuesSWTI_III)
r2Vals <- apply(subset(predictedValuesSWTI_III, select = -Effort), 2, function (x) {
  dat <- data.frame(Predicted = x, Effort = predictedValuesSWTI_III$Effort)
  model <- lm(Effort ~ ., data = dat)
  summary(model)$r.squared
})
r2Vals <- round(r2Vals, digits = 5)
r2Vals <- paste("r2:", r2Vals, sep = "")
predictedValues <- gather(predictedValuesSWTI_III, numBins, Predicted, -Effort)
r2data_txt <- data.frame(label = as.character(r2Vals), numBins = paste(1:length(SWTIresults_III), "Bins"))
ggplot(predictedValues, aes(x = Predicted, y = Effort)) +
  geom_point(shape = 1) + stat_smooth(method = "lm",  se = FALSE, fullrange = TRUE) +
  facet_grid(. ~ numBins, scales = "free") + xlab("Predicted Effort") +
  ylab("Actual Effort") + ggtitle("Goodness of Fit") +
  theme(panel.spacing = unit(1, "lines")) +
  geom_text(data = r2data_txt, size = 3, mapping = aes(x = -Inf, y = -Inf, label = label),
            hjust = -0.1, vjust = -1) + 
  theme_bw()

# Plot cross validation results
MSEdata <- data.frame(NumBins = 1:length(SWTIresults_III), MSE = sapply(SWTIresults_III, function(x) { x$MSE }))
MMREdata <- data.frame(NumBins = 1:length(SWTIresults_III), MMRE = sapply(SWTIresults_III, function(x) { x$MMRE }))
PREDdata <- data.frame(NumBins = 1:length(SWTIresults_III), PRED = sapply(SWTIresults_III, function(x) { x$PRED }))
ggplot(data = MSEdata, aes(x = NumBins, y = log(MSE))) + geom_point(shape = 1) + geom_line() + ggtitle("MSE vs Number of Bins") + 
  theme_bw()
ggplot(data = MMREdata, aes(x = NumBins, y = MMRE)) + geom_point(shape = 1) + geom_line() + ggtitle("MMRE vs Number of Bins") + 
  theme_bw()
ggplot(data = PREDdata, aes(x = NumBins, y = PRED)) + geom_point(shape = 1) + geom_line() + ylab("PRED(0.25)") + ggtitle("PRED(0.25) Results") + 
  theme_bw()

# Plot marginal posteriors for each parameter
for (i in 1:length(SWTIresults_III)) {
  marginalData <- SWTIresults_III[[i]]$model[, !names(SWTIresults_III[[i]]$model) %in% c("(Intercept)", "sigma")]
  if (is.vector(marginalData)) {
    marginalData <- data.frame(l1 = marginalData)
  }
  for (col in names(marginalData)) {
    mean <- mean(marginalData[, col])
    sd <- sd(marginalData[, col])
    peakDensity <- dnorm(mean, mean, sd)
    g <- ggplot(marginalData, aes(x=marginalData[, col])) + 
    geom_histogram(aes(y = ..density..), binwidth = 1, colour="black", fill="white") + 
    stat_function(fun = dnorm, args = list(mean = mean(mean), sd = sd)) + 
    xlab(col) + ggtitle("Posterior Weight", paste(col, i, "bins")) +
    annotate("text", x = mean, y = peakDensity * ((sd/3 *.1) + 1), label = paste("mean:", round(mean,2),",", "sd:", round(sd,2))) + 
    theme_bw()
    print(g)
  }
}
```
SWTII Search Results
```{r swtii, warning = FALSE}
SWTIIresults <- performSearch(6, effort, transactionFiles, c("TL", "TD"))
# Plot classification results
for (i in 1:length(SWTIIresults)) {
  result <- SWTIIresults[[i]]
  df <- as.data.frame(t(subset(result$data, select = -c(Effort))))
  g <- ggplot(data = df, aes(x = rownames(df), y = Aggregate)) + 
    geom_bar(stat = "identity") +
     xlab("Levels") +
    ylab("Counts") +
    ggtitle(paste("Classification Results:", i*2-2+1, "levels")) +
    theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
  cutsVec <- cutsAsVec(result$cuts)
  g <- g + geom_text(data = data.frame(cutsVec), aes(label=cutsVec, col=cutsVec), alpha=0, x=1, y=1) +
  theme(legend.key=element_blank(), legend.title = element_blank()) +
  guides(colour=guide_legend(override.aes=list(size=0)), reverse = TRUE) + 
  theme_bw()
  print(g)
}

#print(SWTIIresults[[5]][["model"]])
# Plot predicted vs. actual effort values
predictedValuesSWTII <- sapply(1:length(SWTIIresults), function(i) {
  predicted <- apply(SWTIIresults[[i]]$data, 1, function(x) {
    blmpredicted <- predict.blm(SWTIIresults[[i]]$model, newdata = as.data.frame(t(x)))
    #blmpredicted*SWTIIresults[[i]]$normFactor
  })
})

colnames(predictedValuesSWTII) <- paste(1:length(SWTIIresults), "Bins")
predictedValuesSWTII <- subset(predictedValuesSWTII, rownames(predictedValuesSWTII) != "Aggregate")
predictedValuesSWTII <- merge(as.data.frame(predictedValuesSWTII), effort, by='row.names', all=TRUE)
rownames(predictedValuesSWTII) <- predictedValuesSWTII$Row.names
predictedValuesSWTII$Row.names <- NULL

r2Vals <- apply(subset(predictedValuesSWTII, select = -Effort), 2, function (x) {
  dat <- data.frame(Predicted = x, Effort = predictedValuesSWTII$Effort)
  model <- lm(Effort ~ ., data = dat)
  summary(model)$r.squared
})
r2Vals <- round(r2Vals, digits = 5)
r2Vals <- paste("r2:", r2Vals, sep = "")
predictedValues <- gather(predictedValuesSWTII, numBins, Predicted, -Effort)
r2data_txt <- data.frame(label = as.character(r2Vals), numBins = paste(1:length(SWTIIresults), "Bins"))
ggplot(predictedValues, aes(x = Predicted, y = Effort)) +
  geom_point(shape = 1) + stat_smooth(method = "lm",  se = FALSE, fullrange = TRUE) +
  facet_wrap(. ~ numBins, scales = "free", nrow=2) + xlab("Predicted Effort") +
  ylab("Actual Effort") + ggtitle("Goodness of Fit") +
  theme(panel.spacing = unit(1, "lines")) +
  geom_text(data = r2data_txt, size = 3, mapping = aes(x = -Inf, y = -Inf, label = label),
            hjust = -1, vjust = -1) + 
  theme_bw()

# Plots cross validation results  
MSEdata <- data.frame(NumBins = 1:length(SWTIIresults), MSE = sapply(SWTIIresults, function(x) { x$MSE }))
MMREdata <- data.frame(NumBins = 1:length(SWTIIresults), MMRE = sapply(SWTIIresults, function(x) { x$MMRE }))
PREDdata <- data.frame(NumBins = 1:length(SWTIIresults), PRED = sapply(SWTIIresults, function(x) { x$PRED }))
ggplot(data = MSEdata, aes(x = NumBins, y = log(MSE))) + geom_point(shape = 1) + geom_line() + ggtitle("MSE vs Number of Bins") + 
  theme_bw()
ggplot(data = MMREdata, aes(x = NumBins, y = MMRE)) + geom_point(shape = 1) + geom_line() + ggtitle("MMRE vs Number of Bins") + 
  theme_bw()
ggplot(data = PREDdata, aes(x = NumBins, y = PRED)) + geom_point(shape = 1) + geom_line() + ylab("PRED(0.25)") + ggtitle("PRED(0.25) Results") + 
  theme_bw()

# Plot marginal posteriors for each parameter
for (i in 1:length(SWTIIresults)) {
  marginalData <- SWTIIresults[[i]]$model[, !names(SWTIIresults[[i]]$model) %in% c("(Intercept)", "sigma")]
  if (is.vector(marginalData)) {
    marginalData <- data.frame(l1 = marginalData)
  }
  for (col in names(marginalData)) {
    mean <- mean(marginalData[, col])
    sd <- sd(marginalData[, col])
    peakDensity <- dnorm(mean, mean, sd)
    g <- ggplot(marginalData, aes(x=marginalData[, col])) + 
    geom_histogram(aes(y = ..density..), binwidth = 1, colour="black", fill="white") + 
    stat_function(fun = dnorm, args = list(mean = mean(mean), sd = sd)) + 
    xlab(col) + ggtitle("Posterior Weight", paste(col, i, "bins")) +
    annotate("text", x = mean, y = peakDensity * ((sd/3 *.1) + 1), label = paste("mean:", round(mean,2),",", "sd:", round(sd,2))) + 
    theme_bw()
    print(g)
  }
}
```
SWTIII Search Results
```{r swtiii, warning = FALSE}
SWTIIIresults <- performSearch(6, effort, transactionFiles, c("TL", "TD", "DETs"))
# Plot classification results
for (i in 1:length(SWTIIIresults)) {
  result <- SWTIIIresults[[i]]
  df <- as.data.frame(t(subset(result$data, select = -c(Effort))))
  g <- ggplot(data = df, aes(x = rownames(df), y = Aggregate)) + 
    geom_bar(stat = "identity") +
      xlab("Levels") +
    ylab("Counts") +
    ggtitle(paste("Classification Results:", i*3-3+1, "levels")) +
    theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
  cutsVec <- cutsAsVec(result$cuts)
  g <- g + geom_text(data = data.frame(cutsVec), aes(label=cutsVec, col=cutsVec), alpha=0, x=1, y=1) +
  theme(legend.key=element_blank(), legend.title = element_blank()) +
  guides(colour=guide_legend(override.aes=list(size=0)), reverse = TRUE) + 
  theme_bw()
  print(g)
}

# Plot predicted vs. actual effort values
predictedValuesSWTIII <- sapply(1:length(SWTIIIresults), function(i) {
  predicted <- apply(SWTIIIresults[[i]]$data, 1, function(x) {
    blmpredicted <- predict.blm(SWTIIIresults[[i]]$model, newdata = as.data.frame(t(x)))
    #blmpredicted*SWTIIIresults[[i]]$normFactor
  })
})

colnames(predictedValuesSWTIII) <- paste(1:length(SWTIIIresults), "Bins")
predictedValuesSWTIII <- subset(predictedValuesSWTIII, rownames(predictedValuesSWTIII) != "Aggregate")
predictedValuesSWTIII <- merge(as.data.frame(predictedValuesSWTIII), effort, by='row.names', all=TRUE)
rownames(predictedValuesSWTIII) <- predictedValuesSWTIII$Row.names
predictedValuesSWTIII$Row.names <- NULL

r2Vals <- apply(subset(predictedValuesSWTIII, select = -Effort), 2, function (x) {
  dat <- data.frame(Predicted = x, Effort = predictedValuesSWTIII$Effort)
  model <- lm(Effort ~ ., data = dat)
  summary(model)$r.squared
})
r2Vals <- round(r2Vals, digits = 5)
r2Vals <- paste("r2:", r2Vals, sep = "")
predictedValues <- gather(predictedValuesSWTIII, numBins, Predicted, -Effort)
r2data_txt <- data.frame(label = as.character(r2Vals), numBins = paste(1:length(SWTIIIresults), "Bins"))
ggplot(predictedValues, aes(x = Predicted, y = Effort)) +
  geom_point(shape = 1) + stat_smooth(method = "lm",  se = FALSE, fullrange = TRUE) +
  facet_wrap(. ~ numBins, scales = "free", nrow=2) + xlab("Predicted Effort") +
  ylab("Actual Effort") + ggtitle("Goodness of Fit") +
  theme(panel.spacing = unit(1, "lines")) +
  geom_text(data = r2data_txt, size = 3, mapping = aes(x = -Inf, y = -Inf, label = label),
            hjust = -1, vjust = -1) + 
  theme_bw()

# Plots cross validation results
MSEdata <- data.frame(NumBins = 1:length(SWTIIIresults), MSE = sapply(SWTIIIresults, function(x) { x$MSE }))
MMREdata <- data.frame(NumBins = 1:length(SWTIIIresults), MMRE = sapply(SWTIIIresults, function(x) { x$MMRE }))
PREDdata <- data.frame(NumBins = 1:length(SWTIIIresults), PRED = sapply(SWTIIIresults, function(x) { x$PRED }))
ggplot(data = MSEdata, aes(x = NumBins, y = log(MSE))) + geom_point(shape = 1) + geom_line() + ggtitle("MSE vs Number of Bins") + 
  theme_bw()
ggplot(data = MMREdata, aes(x = NumBins, y = MMRE)) + geom_point(shape = 1) + geom_line() + ggtitle("MMRE vs Number of Bins") + 
  theme_bw()
ggplot(data = PREDdata, aes(x = NumBins, y = PRED)) + geom_point(shape = 1) + geom_line() + ylab("PRED(0.25)") + ggtitle("PRED vs Number of Bins") + 
  theme_bw()

# Plot marginal posteriors for each parameter
for (i in 1:length(SWTIIIresults)) {
  marginalData <- SWTIIIresults[[i]]$model[, !names(SWTIIIresults[[i]]$model) %in% c("(Intercept)", "sigma")]
  if (is.vector(marginalData)) {
    marginalData <- data.frame(TL1TD1DETs1 = marginalData)
  }

  for (col in names(marginalData)) {
    mean <- mean(marginalData[, col])
    sd <- sd(marginalData[, col])
    peakDensity <- dnorm(mean, mean, sd)
    g <- ggplot(marginalData, aes(x=marginalData[, col])) + 
    geom_histogram(aes(y = ..density..), binwidth = 1, colour="black", fill="white") + 
    stat_function(fun = dnorm, args = list(mean = mean(mean), sd = sd)) + 
    xlab(col) + ggtitle(paste("Posterior Weight", col, i, "bins")) +
    annotate("text", x = mean, y = peakDensity * ((sd/3 *.1) + 1), label = paste("mean:", round(mean,2),",", "sd:", round(sd,2))) + 
    theme_bw()
    print(g)
  }

}
  
```
plot the selected models
```{r modelPlot, warning = FALSE}

TNModelSelector <- 1;
TNModelPredictedValues <- as.data.frame(predictedValuesTN[, c(paste(TNModelSelector, "Bins", sep=" "))])
TNModelData <- TNresults[[TNModelSelector]][["data"]]
TNModelData <- TNModelData[rownames(TNModelData) != "Aggregate", ]
colnames(TNModelPredictedValues) <- c("EUCP")
rownames(TNModelPredictedValues) <- rownames(predictedValuesTN)

SWTIIModelSelector <- 4;
SWTIIModelPredictedValues = as.data.frame(predictedValuesSWTII[, c(paste(SWTIIModelSelector, "Bins", sep=" "))])
SWTIIModelData <- SWTIIresults[[SWTIIModelSelector]][["data"]]
SWTIIModelData <- SWTIIModelData[rownames(SWTIIModelData) != "Aggregate", ]
#print(SWTIIModelData)
colnames(SWTIIModelPredictedValues) <- c("EXUCP")
rownames(SWTIIModelPredictedValues) <- rownames(predictedValuesSWTII)

SWTIIIModelSelector <- 3;
SWTIIIModelPredictedValues = as.data.frame(predictedValuesSWTIII[, c(paste(SWTIIIModelSelector, "Bins", sep=" "))])
SWTIIIModelData <- SWTIIIresults[[SWTIIIModelSelector]][["data"]] 
SWTIIIModelData <- SWTIIIModelData[rownames(SWTIIIModelData) != "Aggregate", ]
colnames(SWTIIIModelPredictedValues) <- c("DUCP")
rownames(SWTIIIModelPredictedValues) <- rownames(predictedValuesSWTIII)

predictedValues <- merge(TNModelPredictedValues, SWTIIModelPredictedValues, by='row.names', all=TRUE)
rownames(predictedValues) <- predictedValues$Row.names
predictedValues$Row.names <- NULL
predictedValues <- merge(predictedValues, SWTIIIModelPredictedValues, by='row.names', all=TRUE)
rownames(predictedValues) <- predictedValues$Row.names
predictedValues$Row.names <- NULL
predictedValues <- merge(predictedValues, effort, by='row.names', all=TRUE)
rownames(predictedValues) <- predictedValues$Row.names
predictedValues$Row.names <- NULL

r2Vals <- apply(subset(predictedValues, select = -Effort), 2, function (x) {
  dat <- data.frame(Predicted = x, Effort = predictedValues$Effort)
  model <- lm(Effort ~ ., data = dat)
  print(summary(model))
  summary(model)$r.squared
})

r2Vals <- round(r2Vals, digits = 5)
r2Vals <- paste("r2:", r2Vals, sep = "")
predictedValues <- gather(predictedValues, models, Predicted, -Effort)
r2data_txt <- data.frame(label = as.character(r2Vals), models = c("EUCP", "EXUCP", "DUCP"))
ggplot(predictedValues, aes(x = Predicted, y = Effort)) +
  geom_point(shape = 1) + stat_smooth(method = "lm",  se = FALSE, fullrange = TRUE) +
  facet_grid(. ~ models, scales = "free") + xlab("Predicted Effort") +
  ylab("Actual Effort") + ggtitle("Goodness of Fit") +
  theme(panel.spacing = unit(1, "lines")) +
  geom_text(data = r2data_txt, size = 3, mapping = aes(x = -Inf, y = -Inf, label = label),
            hjust = -1, vjust = -1)+
  theme_bw()


#plot only DUCP
predictedValuesDUCP <- merge(SWTIIIModelPredictedValues, effort, by='row.names', all=TRUE)
rownames(predictedValuesDUCP) <- predictedValuesDUCP$Row.names
predictedValuesDUCP$Row.names <- NULL

r2Vals <- apply(subset(predictedValuesDUCP, select = -Effort), 2, function (x) {
  dat <- data.frame(Predicted = x, Effort = predictedValuesDUCP$Effort)
  model <- lm(Effort ~ ., data = dat)
  print(summary(model))
  summary(model)$r.squared
})

r2Vals <- round(r2Vals, digits = 5)
r2Vals <- paste("r2:", r2Vals, sep = "")
r2data_txt <- data.frame(label = as.character(r2Vals))

ggplot(predictedValuesDUCP, aes(x = DUCP, y = Effort)) +
  geom_point(shape = 1) + stat_smooth(method = "lm",  se = FALSE, fullrange = TRUE) + xlab("Predicted Effort") +
  ylab("Actual Effort") + ggtitle("Goodness of Fit") +
  theme(panel.spacing = unit(1, "lines")) +
  geom_text(data = r2data_txt, size = 5, mapping = aes(x = -Inf, y = -Inf, label = label),
            hjust = -5, vjust = -1)+
  theme_bw(base_size=20)


#draw example of posterior estimates
  marginalData <- SWTIIIresults[[SWTIIIModelSelector]]$model[, !names(SWTIIIresults[[SWTIIIModelSelector]]$model) %in% c("(Intercept)", "sigma", "normFactor", "sd")]
  
    #for (col in names(marginalData)) {
    means <- apply(marginalData, 2, mean)
    sd <- apply(marginalData, 2, sd)
    labels <- paste(colnames(marginalData), ":", round(means,2),",", round(sd,2))
    print(labels)
    
  colnames(marginalData) <- labels
  
  gatheredData <- gather(marginalData, level, value)
    
    normaldens <- ddply(gatheredData, "level", function(df) {
      values <- seq(min(df$value), max(df$value), length = 100)

      data.frame( 
       value = values,
       density = dnorm(values, mean(df$value), sd(df$value))
      )
    })
    
    ggplot(gatheredData, aes(value))  + 
  geom_histogram(aes(y = ..density..), binwidth = 1, colour="black", fill="white") +
  geom_line(aes(y = density), data = normaldens, colour = "red") +
  facet_wrap(~ level, scales = "free", nrow=2) + xlab("Posterior Estimates") +ylab("Density")
  #geom_text(
  #data    = dat_text,
  #mapping = aes(x = 0, y = 0, label = label),
  #hjust   = -0.1,
  #vjust   = -1
  #)
```



comparison between UCP, COCOMO, a-priori COCOMO
```{r modelPlot, warning = FALSE}
#df <- read.csv("modelEvaluations-8-16-3.csv")
otherSizeMetricsData=modelData[c("Effort", "COCOMO_Estimate", "Priori_COCOMO_Estimate", "UCP")]

ret <- compareBetweenSizeMetrics(TNModelData, SWTIIModelData, SWTIIIModelData, otherSizeMetricsData)
#model1 <- TNresults[[TNModelSelector]][["model"]]
#model2 <- SWTIIresults[[SWTIIModelSelector]][["model"]]
#model3 <- SWTIIIresults[[SWTIIIModelSelector]][["model"]]
#ret <- compareBetweenSizeMetrics(TNModelData, SWTIIModelData, SWTIIIModelData, otherSizeMetricsData, model1, model2, model3)

cvResults <-ret[["cvResults"]]
print(cvResults)

avgPreds <- ret[["avgPreds"]]
print('average improvement by eucp')
print(colMeans(avgPreds[, "EUCP"] - avgPreds[,!colnames(avgPreds) %in% c("Pred")]))
print('average improvement by exucp')
print(colMeans(avgPreds[, "EXUCP"] - avgPreds[,!colnames(avgPreds) %in% c("Pred")]))
print('average improvement by ducp')
print(colMeans(avgPreds[, "DUCP"] - avgPreds[,!colnames(avgPreds) %in% c("Pred")]))
print('average improvement by ucp')
print(colMeans(avgPreds[, "UCP"] - avgPreds[,!colnames(avgPreds) %in% c("Pred")]))
print('average improvement by cocomo')
print(colMeans(avgPreds[, "COCOMO"] - avgPreds[,!colnames(avgPreds) %in% c("Pred")]))
print('average improvement by cocomo.apriori')
print(colMeans(avgPreds[, "COCOMO Apriori"] - avgPreds[,!colnames(avgPreds) %in% c("Pred")]))

#print(mean(avgPreds[, "EXUCP"] - avgPreds[,"UCP"]))
#print(mean(avgPreds[, "EXUCP"] - avgPreds[,"COCOMO"]))
#print(mean(avgPreds[, "EXUCP"] - avgPreds[,"COCOMO Apriori"]))
#print(mean(avgPreds[, "DUCP"] - avgPreds[,"EUCP"]))
#print(mean(avgPreds[, "DUCP"] - avgPreds[,"EXUCP"]))

avgPreds <- data.frame(avgPreds)
print(avgPreds)
meltAvgPreds = melt(avgPreds, id.vars="Pred")
colnames(meltAvgPreds) <- c("Pred", "Method", "Value")

print("melt avg preds info")
print(meltAvgPreds)
ggplot(meltAvgPreds) + theme_bw() + geom_point(aes(x=Pred, y=Value, group=Method,color=Method),size=3)+ xlab("Relative Deviation (%)") +
				ylab("Percentage of Estimates <= x%")+ theme(legend.position="bottom")

print("melt avg preds info as lines and smooth function")
ggplot(meltAvgPreds) + theme_bw() + 
		geom_line(aes(y=Value, x=Pred, group=Method,color=Method)) +
		stat_smooth(aes(y=Value, x=Pred, group=Method,color=Method), method = lm, formula = y ~ poly(x, 10), se = FALSE)+ xlab("Relative Deviation (%)") +
		ylab("Percentage of Estimates <= x%")+ theme(legend.position="bottom")


print("melt avg preds info as dots and smooth function")
ggplot(meltAvgPreds) + theme_bw() + 
		geom_point(aes(x=Pred, y=Value, group=Method,color=Method,shape=Method),size=1.5) +
		scale_shape_manual(values=c(0,1,2,3,4,5,6))+
		stat_smooth(aes(x=Pred, y=Value, group=Method,color=Method), method = lm, formula = y ~ poly(x, 10), se = FALSE)+ xlab("Relative Deviation (%)") +
		ylab("Percentage of Estimates <= x%")+ theme(legend.position="bottom")

#compare DUCP and UCP
avgPreds_DUCP_UCP <- avgPreds[, c("DUCP", "UCP", "Pred")]
#print(avgPreds)
meltAvgPreds_DUCP_UCP = melt(avgPreds_DUCP_UCP, id.vars="Pred")
colnames(meltAvgPreds_DUCP_UCP) <- c("Pred", "Method", "Value")

print("melt avg preds info as dots and smooth function")
ggplot(meltAvgPreds_DUCP_UCP) + theme_bw() + 
		geom_point(aes(x=Pred, y=Value, group=Method,color=Method,shape=Method),size=1.5) +
		scale_shape_manual(values=c(0,1,2,3,4,5,6))+
		stat_smooth(aes(x=Pred, y=Value, group=Method,color=Method), method = lm, formula = y ~ poly(x, 10), se = FALSE)+ xlab("Relative Deviation (%)") +
		ylab("Percentage of Estimates <= x%")+ theme(legend.position="bottom")
```

save the parameters to file
```{r save parameters, warning = FALSE}

#source("transaction_weights_calibration3.R")
trainedModels = list()
trainedModels[["TNModel"]] = TNresults[[TNModelSelector]]
trainedModels[["SWTIIModel"]] = SWTIIresults[[SWTIIModelSelector]]
trainedModels[["SWTIIIModel"]] = SWTIIIresults[[SWTIIIModelSelector]]

saveRDS(trainedModels, file="train_models.rds")

#extract parameters for NT
trainedModelParameters = list()
TNModelParameters = list()
TNModelParameters[["effortAdj"]] = c(mean(TNresults[[TNModelSelector]][["model"]][["normFactor"]]), var(TNresults[[TNModelSelector]][["model"]][["normFactor"]]))
TNModelParameters[["sigma"]] = c(mean(TNresults[[TNModelSelector]][["model"]][["sd"]]), var(TNresults[[TNModelSelector]][["model"]][["sd"]]))
TNModelParameters[["cuts"]] = list()
for(i in rownames(TNresults[[TNModelSelector]][["cuts"]])){
  TNModelParameters[["cuts"]][[i]] = TNresults[[TNModelSelector]][["cuts"]][i,]
}
levels <- names(TNresults[[TNModelSelector]][["model"]])
levels <- levels[!levels %in% c("sigma", "sd", "normFactor")]
TNModelParameters[["levels"]] = list()
for(i in levels){
  TNModelParameters[["levels"]][[i]] = c(mean(TNresults[[TNModelSelector]][["model"]][[i]]), var(TNresults[[TNModelSelector]][["model"]][[i]]))
}

trainedModelParameters[["EUCP"]] = TNModelParameters

#extract parameters for SWTII
SWTIIModelParameters = list()
SWTIIModelParameters[["effortAdj"]] = c(mean(SWTIIresults[[SWTIIModelSelector]][["model"]][["normFactor"]]), var(SWTIIresults[[SWTIIModelSelector]][["model"]][["normFactor"]]))
SWTIIModelParameters[["sigma"]] = c(mean(SWTIIresults[[SWTIIModelSelector]][["model"]][["sd"]]), var(SWTIIresults[[SWTIIModelSelector]][["model"]][["sd"]]))
SWTIIModelParameters[["cuts"]] = list()
for(i in rownames(SWTIIresults[[SWTIIModelSelector]][["cuts"]])){
  SWTIIModelParameters[["cuts"]][[i]] = SWTIIresults[[SWTIIModelSelector]][["cuts"]][i,]
}
#print(SWTIIModelParameters[["cuts"]])
levels <- names(SWTIIresults[[SWTIIModelSelector]][["model"]])
levels <- levels[!levels %in% c("sigma", "sd", "normFactor")]
SWTIIModelParameters[["levels"]] = list()
for(i in levels){
  SWTIIModelParameters[["levels"]][[i]] = c(mean(SWTIIresults[[SWTIIModelSelector]][["model"]][[i]]), var(SWTIIresults[[SWTIIModelSelector]][["model"]][[i]]))
}

trainedModelParameters[["EXUCP"]] = SWTIIModelParameters

#extract parameters for SWTIII
SWTIIIModelParameters = list()
SWTIIIModelParameters[["effortAdj"]] = c(mean(SWTIIIresults[[SWTIIIModelSelector]][["model"]][["normFactor"]]), var(SWTIIIresults[[SWTIIIModelSelector]][["model"]][["normFactor"]]))
SWTIIIModelParameters[["sigma"]] = c(mean(SWTIIIresults[[SWTIIIModelSelector]][["model"]][["sd"]]), var(SWTIIIresults[[SWTIIIModelSelector]][["model"]][["sd"]]))
SWTIIIModelParameters[["cuts"]] = list()
for(i in rownames(SWTIIIresults[[SWTIIIModelSelector]][["cuts"]])){
  SWTIIIModelParameters[["cuts"]][[i]] = SWTIIIresults[[SWTIIIModelSelector]][["cuts"]][i,]
}
levels <- names(SWTIIIresults[[SWTIIIModelSelector]][["model"]])
levels <- levels[!levels %in% c("sigma", "sd", "normFactor")]
SWTIIIModelParameters[["levels"]] = list()
for(i in levels){
  SWTIIIModelParameters[["levels"]][[i]] = c(mean(SWTIIIresults[[SWTIIIModelSelector]][["model"]][[i]]), var(SWTIIIresults[[SWTIIIModelSelector]][["model"]][[i]]))
}

trainedModelParameters[["DUCP"]] = SWTIIIModelParameters

write(jsonlite::toJSON(trainedModelParameters,pretty = TRUE,auto_unbox = TRUE), "trained_model_parameters.json")

```